### ISSUE TITLE
Regression - Loading issue with Below The Root

### ISSUE THREAD

**Issue by dspiteri** [MiSTer-devel/C64_MiSTer#166] opened 2024-01-19 08:50 UTC
Observed on C64_20240110.rbf when loading Below the Root (GB64 version) the game crashes with DolphinDos, loads OK with stock kernal and with speeder carts. Also noticed on Windham Classics Alice in Wonderland (GB64 version).

This issue isn't present on C64_20231208.rbf. I also observed crashing for the same game on the c128 core with JiffyDos enabled but can load if I force 1541. This also worked before the update.

**Comment by sorgelig** [comment] 2024-01-22 11:59
@eriks5 i believe it's broken by CIA tweaks.

**Comment by eriks5** [comment] 2024-01-22 19:24
@sorgelig I can reproduce the issue with C64_unstable_20240102_223f9c and the CIA changes were merged on Jan 6, so I don't think it's related.

C64_unstable_20240101_188e63 does not have the issue, so it appears to be due to the disk change changes that were committed on Jan 2.

**Comment by sorgelig** [comment] 2024-01-23 06:40
Actually i don't see a problem with this game.
After changing the disk, try to press the space bar after 2-3 seconds, not immediately

**Comment by sorgelig** [comment] 2024-01-23 07:03
Alice in Wonderland also works fine if you press space bar not immediately. 
Some games/demos require longer disk swap process, so core has been tweaked for that. As a side effect, for games requiring disk swap confirmation, wait for couple seconds and then confirm.

May be i need to block the keyboard while disk is in swapping process...

**Comment by eriks5** [comment] 2024-01-23 07:05
Blocking the keyboard might be an option, but some form of visual feedback might be better. Maybe the MiSTer UI should remain open during the disk change delay?

**Comment by sorgelig** [comment] 2024-01-23 09:10
UI can't be controlled by core.
Any visual feedback should be made by core itself, like overlay.

**Comment by sorgelig** [comment] 2024-01-27 13:01
Try upcoming unstable build.
LED is ON while disk swapping is in process.

**Comment by sorgelig** [comment] 2024-01-27 13:05
I wonder, on real C64 what will happen in these games when you remove disk and press SPACE without disk

**Closed as completed** 2024-03-05 02:39 UTC
